version: '3'
services:
  service-envoy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "8081:8081"
    expose:
      - "80"
      - "8081"
    networks:
      - my-network-name
    links:
      - goserver

  goserver:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:7000"
    expose:
      - "7000"
    networks:
      - my-network-name

networks:
  my-network-name:
