version: '2'
services:
  front-envoy:
    build:
      context: ./proxy
      dockerfile: Dockerfile-frontproxy
    links:
      - "goserver"
    volumes:
      - ./front-envoy.json:/etc/front-envoy.json
    ports:
      - "8000:80"
      - "8001:8001"

  goserver:
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "8080"
