version: '3'
services:

  front-envoy:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "9000:80"
      - "9001:8081"
    expose:
      - "80"
      - "8081"
    networks:
      - envoymesh

  service-envoy:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "7778:8081"
    expose:
      - "80"
      - "8081"
    networks:
      - backendnetwork
      - envoymesh

  goserver:
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - "7000"
    networks:
      - backendnetwork

networks:
  backendnetwork:
  envoymesh:
