version: '2'
services:
  service-envoy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    links:
      - "goserver"
    networks:
      - envoymesh
    ports:
      - "8000:80"
      - "8001:8001"
    expose:
      - "80"
      - "8001"

  goserver:
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      - envoymesh
    ports:
      - "8080:8080"
    expose:
      - "8080"

networks:
  envoymesh: {}
